#==================== 安全配置 ============================
spring:
  profiles:
    active: test
#==================== 多环境（双节点） ============================

server:
  port: 8101
  servlet:
    session:
      timeout: 3600
  tomcat:
    uri-encoding: utf-8
    


  #============热部署============
  devtools:
    restart:
      enabled: false #热部署生效1
      additional-paths: java/com/**  #设置重启的目录
      exclude: resources/**,static/**,templates/**  #该目录下的内容修改不重启