
server:
  port: 8010
  servlet:
    session:
      timeout: 3600
  tomcat:
    uri-encoding: utf-8
    

#==================== Eureka Client============================
eureka:
  client:
    register-with-eureka: true #不向Eureka中注册自己
    service-url:
      defaultZone: http://zh:zh12@localhost:8801/eureka/ #这里zh:zh12 是自己添加的安全认证，不想添加可以直接在eurekaServer端和这里统一去掉
  instance:
    hostname: localhost #配置使用主机名注册服务
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@ #可以修改eureka上status的默认描述信息
    prefer-ip-address: true       #可以将IP注册到Eureka Server上，而如果不配置就是机器的主机名
    leaseRenewalIntervalInSeconds: 10 #租期更新时间间隔(默认30秒).每间隔10s，向服务端发送一次心跳，证明自己依然”存活“
    leaseExpirationDurationInSeconds: 30 #租期到期时间(默认90秒).告诉服务端，如果我30s之内没有给你发心跳，就代表我“死”了，将我踢出掉